modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/TheGridExpert/VampiresDelight/issues"
license="${mod_license}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_display_name}"
displayURL = "https://github.com/TheGridExpert/VampiresDelight"
logoFile="logo.png"
logoBlur=false
itemIcon = "vampiresdelight:dark_stone_stove"
configBackground = "vampiresdelight:textures/block/dark_stone_small_bricks.png"
credits="${credits}"
authors="GridExpert"
enumExtensions="META-INF/enumextensions.json"
description='''
Makes Vampirism and Farmer's Delight more compatible
'''

[[dependencies.vampiresdelight]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vampiresdelight]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vampiresdelight]]
modId="vampirism"
type="required"
versionRange="${vampirism_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vampiresdelight]]
modId="farmersdelight"
type="required"
versionRange="${farmersdelight_version_range}"
ordering="NONE"
side="BOTH"